### ISSUE TITLE
Archivo de "drills"

### ISSUE THREAD

**Issue by panfri787** [AnakinTF/PCB-DES#1]
Hola,

Estaba usando estos ficheros gerber para pedir a un proveedor de PCB las placas de los cartuchos y me han indicado que no tienen los archivos con los agujeros en la placa. ¿Son necesarios? De ser necesarios, ¿Los podríais publicar?

Gracias.

**Comment by AnakinTF** [comment]
Hola!
Estos ficheros están completos.
